#!/bin/bash

# The Feliz installation scripts for Arch Linux
# 21 April 2016

# running - Various functions called during installation

# Developed by Elizabeth Mills, incorporating some code adapted from
# the Evo/Lution script by Carl Duff and AUI scripts by HelmuthDU.

# -------------------------      -------------------------
# Functions           Line       Functions           Line
# -------------------------      -------------------------
# PrintOne              25       SetGrubDevice        116
# TPecho                29       MountPartitions      130
# arch_chroot           33       InstallKernel        188
# DisplayProgress       37       AddCodecs            218
# ProgressArray         56       McInitCPIO           221
# Bugger                81       InstallLuxuries      231
# SetKernel             85       UserAdd              254
# ConfirmVbox           97       Passwords            277
# ConfirmReview        108       Finish               332

PrintOne() {  # Arguments: "Component" "Patient"
  dialog --backtitle "$Backtitle" --title " - Information - " --no-shadow --infobox "\n$1\n$2" 6 50 ; sleep 1 &
}

TPecho() { # For compatibility with Cliff
    PrintOne "$1" "$2"
}

arch_chroot() {  # From Lution AIS
  arch-chroot /mnt /bin/bash -c "${1}" &>> feliz.log
}

DisplayProgress() {  # Displays timed progress bar for longer processes
  Estimate=$2           # Numeric argument = multiple of 10
  local Message="$1"        # Text passed to appear above progress bar
  local Sleep=$(( $Estimate / 10 )) # Set sleep period to one tenth of total time
  local Percent=0
  (
  until [ $Percent -gt 100 ]
  do
    echo "XXX"
    echo $Percent
    echo "$Message\nProcessing may continue after gauge shows 100%\nPlease be patient ..."
    echo "XXX"
    Percent=`expr $Percent + 10`
    sleep $Sleep
  done
  ) |
  dialog --backtitle "$Backtitle" --title " - Progress - " --no-shadow --gauge "" 9 60 0 &
}

ProgressArray() { # For installing multiple programs with pacstrap and displaying gauge
  local Title="$1"
  # Receives PassArray comprising all the programs
  # 1) Count items in the array
  n=${#PassArray[*]};
  # 2) Redirect dialog commands input using substitution
  dialog --backtitle "$Backtitle" --title " - $Title - " --no-shadow --gauge "" 8 60 < <(
  # 3) set counter - it will increase on each parse
   i=0
  # 4) read each item from the array
  for f in "${PassArray[@]}"
  do
    # ... calculate progress
    PCT=$(( 100*(++i)/n ))
    # ... update dialog box
    echo "XXX"
    echo "$PCT"
    echo "\n  Installing $f"
    echo "XXX"
    # ... install $f
    pacstrap /mnt $f &>> feliz.log
  done
  )
}

MountPartitions() {
  case $RootType in
  "") echo "Not formatting root partition" >> feliz.log
  ;;
  *) PrintOne "Preparing and mounting partitions" ""
    umount ${RootPartition} /mnt >/dev/null &>> feliz.log
    # Check if replacing existing ext3/4 partition with btrfs
    CurrentType=`file -sL ${RootPartition} | grep 'ext\|btrfs' | cut -c26-30` &>> feliz.log
    if [ ${CurrentType} ] && [ $RootType = "btrfs" ] && [ ${CurrentType} != "btrfs" ]; then
      btrfs-convert ${RootPartition} &>> feliz.log
    elif [ $RootType = "btrfs" ]; then
      mkfs.btrfs -f ${RootPartition} &>> feliz.log
    else
      Partition=`echo $RootPartition | cut -c 6-` 2>> feliz.log
      Label="${LabellingArray[${Partition}]}"
      if [ -n "${Label}" ]; then
        Label="-L ${Label}"
      fi
      mke2fs ${Label} -t ${RootType} ${RootPartition} &>> feliz.log
    fi
  esac
  mount ${RootPartition} /mnt &>> feliz.log # eg: mount /dev/sda1 /mnt
  if [ ${SwapPartition} ]; then
    swapoff -a &>> feliz.log
    if [ $MakeSwap = "Y" ]; then
      Partition=`echo $SwapPartition | cut -c 6-`
      Label="${LabellingArray[${Partition}]}"
      if [ -n "${Label}" ]; then
        Label="-L ${Label}"
      fi
      mkswap ${Label} ${SwapPartition} &>> feliz.log # eg: mkswap -L Arch-Swap /dev/sda2
    fi
    swapon ${SwapPartition} &>> feliz.log # eg: swapon /dev/sda2
  fi
  local Counter=0
  for id in ${AddPartList}
  do
    umount ${id} /mnt${AddPartMount[$Counter]} >/dev/null &>> feliz.log
    mkdir -p /mnt${AddPartMount[$Counter]} &>> feliz.log  # eg: mkdir -p /mnt/home
    # Check if replacing existing ext3/4 partition with btrfs
    CurrentType=`file -sL ${AddPartType[$Counter]} | grep 'ext\|btrfs' | cut -c26-30`
    if [ ${AddPartType[$Counter]} = "btrfs" ] && [ ${CurrentType} != "btrfs" ]; then
      btrfs-convert ${id} &>> feliz.log
    elif [ ${AddPartType[$Counter]} = "btrfs" ]; then
      mkfs.btrfs -f ${id} &>> feliz.log
    elif [ ${AddPartType[$Counter]} != "" ]; then
      Partition=`echo ${id} | cut -c 6-`
      Label="${LabellingArray[${Partition}]}"
      if [ -n "${Label}" ]; then
        Label="-L ${Label}"
      fi
      mke2fs ${Label} -t ${AddPartType[$Counter]} ${id} &>> feliz.log # eg: mke2fs -L Arch-Home -t ext4 /dev/sda3
    fi
    mount ${id} /mnt${AddPartMount[$Counter]} &>> feliz.log # eg: mount /dev/sda3 /mnt/home
    Counter=$((Counter+1))
  done
}

InstallKernel() { # Kernel and some other core systems
  DisplayProgress "Installing shell" 40
  pacstrap /mnt base-devel bash &>> feliz.log
  # Create array of all the programs to pass to installing function
  PassArray=() # Ensure array is empty
  PassArray=( btrfs-progs cryptsetup dhcpcd gksu inetutils iproute2 iputils jfsutils licenses logrotate lvm2 mdadm netctl ntp pciutils pcmciautils procps-ng psmisc s-nail systemd-sysvcompat usbutils wget xfsprogs zip nano openssh reiserfsprogs screenfetch unrar unzip vi vim xarchiver xorg-xedit xterm )
  ProgressArray " Installing cli tools " # Install each one using pacstrap

  DisplayProgress "Installing man pages" 20
  pacstrap /mnt man-db man-pages &>> feliz.log

  # Enable sshd
  arch_chroot "systemctl enable sshd.service" >/dev/null

  case $Kernel in
  1) DisplayProgress "Installing LTS kernel" 50
    pacstrap /mnt linux-lts &>> feliz.log
    ;;
  *) DisplayProgress "Installing Latest kernel" 50
    pacstrap /mnt linux &>> feliz.log
  esac
  if [ -n ${IsInVbox} ]; then # Installing in Virtualbox
    pacstrap /mnt virtualbox-guest-utils &>> feliz.log
    pacstrap /mnt virtualbox-guest-modules-arch &>> feliz.log
    echo blacklist i2c_piix4 > /mnt/etc/modprobe.d/modprobe.conf 2>> feliz.log  # To overcome piix4 Virtualbox error
    cp virtualbox.conf /mnt/etc/modules-load.d/ 2>> feliz.log
  fi
 # PrintOne "Installing opensource video drivers" ""
  pacstrap /mnt xf86-video-vesa xf86-video-nouveau &>> feliz.log # Install opensource video drivers
}

AddCodecs() {
  PassArray=() # Ensure the array is empty
  PassArray=( a52dec autofs faac faad2 flac lame libdca libdv libmad libmpeg2 libtheora libvorbis libxv wavpack x264 gstreamer0.10-plugins pulseaudio pulseaudio-alsa libdvdcss libdvdread libdvdnav dvd+rw-tools dvdauthor dvgrab flashplugin b43-fwcutter ipw2100-fw ipw2200-fw zd1211-firmware iw wireless_tools wpa_actiond dialog xorg-server-utils xorg-xinit xorg-twm xf86-input-synaptics gvfs gamin )
  ProgressArray "Adding Codecs, graphics, etc" # Display gauge while installing with pacstrap
}

McInitCPIO() { # Appropriate mkinitcpio for kernel
  DisplayProgress "Running mkinitcpio" 10
  if [ $Kernel = "1" ]; then
    arch_chroot "mkinitcpio -p linux-lts"
  else
    arch_chroot "mkinitcpio -p linux"
  fi
}

InstallLuxuries() { # Install Yaourt, Openbox, LightDM and apps
  TPecho "Modifying pacman.conf and installing Yaourt"
  cp pacman.conf /mnt/etc 2>> feliz.log # For installed system
  cp pacman.conf /etc 2>> feliz.log     # For installer
  pacman-key --init &>> feliz.log
  pacman-key --populate archlinux &>> feliz.log
  pacman -Sy &>> feliz.log              # Update
  pacstrap /mnt yaourt &>> feliz.log

  TPecho "Installing LightDM and greeter" ""
  pacstrap /mnt lightdm lightdm-gtk-greeter &>> feliz.log
  arch_chroot "systemctl -f enable lightdm.service"
  # Set greeter
  sed -i '/greeter-session=/ c greeter-session=lightdm-gtk-greeter' /etc/lightdm/lightdm.conf
  # Openbox
  DisplayProgress "Installing 'Openbox' window manager and components" 20
  pacstrap /mnt openbox obmenu obconf compton tint2 &>> feliz.log
  # Applications ...
  pacstrap /mnt abiword epiphany galculator gnome-mahjongg gnumeric leafpad lxterminal &>> feliz.log
  pacstrap /mnt nitrogen pavucontrol pcmanfm scrot sol xfce4-screenshooter &>> feliz.log

  TPecho "Installing Conky"
  pacstrap /mnt conky &>> feliz.log
}

UserAdd() {
  TPecho "Adding user '${UserName}' and setting up groups"
  arch_chroot "useradd ${UserName} -m -g users -G wheel,storage,power,network,video,audio,lp -s /bin/bash"
  # Set up basic configuration files and permissions for user
  arch_chroot "cp /etc/skel/.bashrc /home/${UserName}"
  arch_chroot "chown -R ${UserName}:users /home/${UserName}"
  sed -i '/%wheel ALL=(ALL) ALL/s/^#//' /mnt/etc/sudoers 2>> feliz.log
}

SetRootPassword() {
  Backtitle="Success! Finished installing in $DIFFMIN minutes and $DIFFSEC seconds"
  Repeat="Y"
  ExtraMessage=""
  while [ $Repeat = "Y" ]
  do
    dialog --backtitle "$Backtitle" --title " - Passwords - " --nocancel \
     --insecure --passwordbox "$ExtraMessage\nEnter a password for root" 10 40 2> output.file
    Pass1=`cat output.file`
    dialog --backtitle "$Backtitle" --title " - Passwords - " --nocancel \
      --insecure --passwordbox "Re-enter password for root" 8 40 2> output.file
    Pass2=`cat output.file`
    if [ -z ${Pass1} ] || [ -z ${Pass2} ]; then
      ExtraMessage="Passwords cannot be blank. Try again ..."
      continue
    fi
    if [ $Pass1 = $Pass2 ]; then
     echo -e "${Pass1}\n${Pass2}" > /tmp/.passwd
     arch_chroot "passwd root" < /tmp/.passwd &>> feliz.log
     rm /tmp/.passwd &>> feliz.log
     Repeat="N"
    else
      ExtraMessage="Passwords don't match. Try again"
    fi
  done
  rm output.file
}

SetUserPassword() {
  Repeat="Y"
  ExtraMessage=""
  while [ $Repeat = "Y" ]
  do
    dialog --backtitle "$Backtitle" --title " - Passwords - " --nocancel\
      --insecure --passwordbox "$ExtraMessage\nEnter a password for $UserName" 10 40 2> output.file
    Pass1=`cat output.file`
    dialog --backtitle "$Backtitle" --title " - Passwords - " --nocancel \
      --insecure --passwordbox "Re-enter password for ${UserName}" 8 40 2> output.file
    Pass2=`cat output.file`
    if [ -z ${Pass1} ] || [ -z ${Pass2} ]; then
      ExtraMessage="Passwords cannot be blank. Try again"
      continue
    fi
    if [ $Pass1 = $Pass2 ]; then
      echo -e "${Pass1}\n${Pass2}" > /tmp/.passwd
      arch_chroot "passwd ${UserName}" < /tmp/.passwd &>> feliz.log
      rm /tmp/.passwd &>> feliz.log
      Repeat="N"
    else
      ExtraMessage="Passwords don't match. Try again"
    fi
  done
  rm output.file
}

DisplayFinished() {
  dialog --backtitle "$Backtitle" --no-shadow --msgbox "\nCongratulations, installation is complete, and the FelizBang installer will now shut down.\nRemember to remove the FelizBang disk before restarting.\nHave fun." 10 55
}
